language: go

go:
  - 1.3

install:
  - go get -t -v ./...
  - go install github.com/onsi/ginkgo/ginkgo
  - curl -L https://github.com/coreos/etcd/releases/download/v0.4.6/etcd-v0.4.6-linux-amd64.tar.gz | tar zxf - -C /tmp
  - mv /tmp/etcd-v0.4.6-linux-amd64/etcd $HOME/gopath/bin
  - go get github.com/apcera/gnatsd

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

script: ginkgo -r -race -failOnPending -randomizeAllSpecs
