language: go

go:
  - 1.3

install:
  - go get -t -v ./...
  - go install github.com/onsi/ginkgo/ginkgo

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

script: ginkgo -r -race -failOnPending -randomizeAllSpecs
